### ISSUE TITLE
Duplicate descriptions in data dictionary

### ISSUE THREAD

**Issue by carrrson** [CareSet/COVID_Hospital_PUF#15]
Hi, thank you for all of your work on this dataset and documentation, and I hope this is the right place to post about this issue.

I have been working with this dataset and noticed a few places where the [data dictionary](https://healthdata.gov/covid-19-reported-patient-impact-and-hospital-capacity-facility-data-dictionary) gives duplicate descriptions for different variables. I see that they point to different areas of the [FAQ document](https://www.hhs.gov/sites/default/files/covid-19-faqs-hospitals-hospital-laboratory-acute-care-facility-data-reporting.pdf), but it would be helpful to have an accurate description. 

The variable pairs I noticed this for are:
`all_adult_hospital_beds_7_day_sum` + `all_adult_hospital_inpatient_beds_7_day_sum`
`total_staffed_adult_icu_beds_7_day_avg` +`icu_beds_used_7_day_avg`
`previous_day_admission_adult_covid_confirmed_70-79_7_day_sum` + `previous_day_admission_adult_covid_suspected_70-79_7_day_sum`
`icu_beds_used_7_day_sum` + `total_icu_beds_7_day_sum`

**Comment by oisact** [comment]
`all_adult_hospital_inpatient_beds_7_day_sum` description is incorrect. It should not include `outpatient` or `ED`.
`total_staffed_adult_icu_beds_7_day_avg` description is incorrect. It should specify `adult`.
`previous_day_admission_adult_covid_confirmed_70-79_7_day_sum` description is incorrect. It should say `confirmed` instead of `suspected`.
`icu_beds_used_7_day_sum` is incorrect. It should be referencing FAQ 6.a.

**Comment by ftrotter** [comment]
Documenting this as a "known bug"
