### ISSUE TITLE
Staffing levels?

### ISSUE THREAD

**Issue by CarlaAstudillo** [CareSet/COVID_Hospital_PUF#5]
Hi, 

I'm a data reporter at the Texas Tribune. Thank you so much for making this available to us. And that Readme is really helpful. I have a question:

> Every day most hospitals in the U.S. are required to report information on the following topics to the federal government:
> 
> Hospital capacity, including information on ICU capacity and available ventilators
> **Staffing levels, including any shortages**
> How many patients are coming into the hospital with confirmed or suspected COVID-19 cases
> Many other relevant details that public health officials need to properly coordinate COVID responses

I'm mostly curious about the staffing levels, and when I saw the column names, I didn't see one that alluded to staffing levels or shortages. Is that not included in this initial dataset or is that something we can calculate using the existing columns in the dataset. Thank you so much!

Take care,
Carla

**Comment by ftrotter** [comment]
This is an excellent question and (like many good questions) has a very complex answer. 
The data fields represent analysis on reports submitted by the hospitals for bed counts. 

The way these should be filled in is detailed precisely in the COVID Reporting Requirements FAQ here: 
https://www.hhs.gov/sites/default/files/covid-19-faqs-hospitals-hospital-laboratory-acute-care-facility-data-reporting.pdf

Reading this, it is obvious that there is no definition of what a "staffed" bed means. 
I suspect that this is an industry term-of-art that is likely rooted in some other HHS/CMS regulation.. and it would be useful to find that for reference (I will see if I can)..

But in any case, this is also an area of interpretation. Each hospital is implicitly deciding what a "staffed bed" counts as. The delineation between a "staffed bed" and "not staffed bed" is hugely critical for proper interpretation of the file, however, and makes a comparison to other data sources that list "bed counts" for hospitals difficult. 

This is also (generally) the reason why the number of beds might change from week to week... as the staffing fluctuates. We also know, however, that there are some cases in which emergency infrastructure improvements actually do result in additional ICU facilities, however, and there is nothing in the reporting that I am aware of that distinguishes between an increase in bed count due to staffing changes, vs infrastructure changes. 

This is another good question that I will flag for attention from the government folks!! Obviously, if they answer you should ignore what I say and trust what they say. My understanding of the file is admittedly an inch deep and a mile wide..
-FT

**Comment by ftrotter** [comment]
FYI I have added a new question regarding the changing bed counts to the FAQ in order to provide some more clarity...

**Comment by CarlaAstudillo** [comment]
Thank you so much for clarifying about staffed beds and bed counts. That's good information to keep in mind. 

I guess I was also hoping that the [`Critical staffing shortage today` columns 23-25](https://www.hhs.gov/sites/default/files/covid-19-faqs-hospitals-hospital-laboratory-acute-care-facility-data-reporting.pdf) would be included, but that doesn't seem to be the case. Although now that it is optional after Nov. 4, it wouldn't be as helpful anyway.

**Comment by ftrotter** [comment]
Ok.  I have more definitive answers on these topics. 

For now, the "critical staffing shortage field" is not part of the release. I believe (but cannot be sure) that this was likely due to concerns from the hospitals/hospital associations, which do not want to release data that could be used to make hospitals look bad. Withholding that variable from the per-facility level reporting would have made the whole release more palatable to hospitals (I imagine). The one thing I am sure of is that the whole reporting process is a partnership with the hospitals and the Federal team handling the reporting absolutely cares what they think, and does not want to haphazardly do something which might cause unnessecary drama at local facilities. I suspect that this was at the root of withholding this field.. but I cannot go on record with this answer until that becomes a clearly stated position from someone at HHS or USDS, and so far that has not happened. 

Personally, however, I do plan to push for additional data around this, at some point. I am hesitant to give a FOIA request to a data team that is doing far more than they would have to if we were interfacing through a Federal Judge, but at some point I think the staffing shortage data needs to come out. I am not sure if this is something that should wait until after the surge has passed however, since it could lead to hospitals pulling out of the reporting process. Which is to say, I certainly have the concern that protecting the reporting pipeline itself is more important than full transparency at this time. HHS has used a medicare mandate to ensure that hospitals "must" report. But that stick is almost too big. Everyone would lose if a hospital stopped reporting, and it is my understanding that when the reporting was voluntary (i.e. before the Medicare mandate) many hospitals were told "this data will never be released on a per-hospital basis". So pissing off the hospitals can backfire badly... 

As for what a staffed bed is. I do have formal confirmation that a staffed bed is an industry term of art, and that there is a specific staffing standard that the reporting is explicitly mandating. Which means that the meaning of "staffed bed" is technically up to each individual hospital, but is enough of an industry-standard term that most hospitals are likely reporting in a very similar way. 

The reality is that any new reporting transparency creates new incentives. Lots of evidence has shown that reporting transparency on surgery has had the impact of surgeons avoiding more risky cases. What we do not want to see is hospitals changing how they report COVID capacity in order to appear to not be overwhelmed in the reporting, even though this is one of the primary ways in which additional resources might be sent to them if they are in fact overwhelming. 

All of which is to say, these transparency efforts, in the middle of a national emergency, are a balancing act, and there are dozens of not immediately obvious trade-offs that are being made. I have to admit that I am a little bit relieved that the majority of these strategic transparency decisions are not on my personal plate. Most of them are damned-if-you-do vs damned-if-you-don't vs am-I-damned?-hell-if-I-know decisions.

-ft

**Comment by CarlaAstudillo** [comment]
This is great background on this. Thank you so much for contacting HHS and getting some of these questions answered. Let me know if anything comes out re: the "critical staffing shortage" field. I completely understand the damned-if-you-do vs. damned-if-you-don't situation in transparency, and I'll let my editors know this background. Thank you again! This has been extremely helpful.
