### ISSUE TITLE
Archiving historical data?

### ISSUE THREAD

**Issue by CarlaAstudillo** [CareSet/COVID_Hospital_PUF#6]
Hi again,

One more question from me. From what I got from the Readme is that this data is set to be released weekly. Will the historical data provided in previous weeks be stored or archived anywhere for easy download or will the csv flat file be overridden with the latest weekly data every week? Thank you!

Take care,
Carla

**Comment by ftrotter** [comment]
The file already has historical data in it. So the file should only "grow" from here. One thing that is not yet clear is how they will be handling data adjustments. We suspect that there will be one file that has "the latest and most correct picture of historical values" and perhaps another that shows "what was reported at the time". 

Apparently, the technical detail on this is due to hospitals who miss the 24 hour window for reporting immediately before the weekly reporting cutoff. So if you fail to report on a Thursday, and the report is run on a Friday, then in that Monday release only 6 days of data will be included. But then the next Mondays release will include the data for the original Thursday. 

Whether or not they release a historical file in the future, it is probably a good idea to archive each file release, just so you  can be aware of minor changes... 

Is this level of detail helpful?

**Comment by CarlaAstudillo** [comment]
Ah yes! I see it now with the "collection_week" column. My bad. 

But yeah, good point about the data adjustments. I'll be sure to archive each file release just so I can keep track. Thank you so much!

**Comment by ftrotter** [comment]
I have also gotten explicit confirmation that revisions to the data will use the revisions tab in healthdata.gov. 
You can see the tab in action here: https://healthdata.gov/node/3542411/revisions
For the hospital reporting metadata PUF (which was the first hospital-identified data release to come out a month or so ago)

**Comment by CarlaAstudillo** [comment]
I'll bookmark that link. Thank you so much.

**Comment by ftrotter** [comment]
Hey, just an FYI, this url for this resource has changed. Not 100% sure, but it looks like the URL is now...

https://healthdata.gov/d/ewep-8fwa

HTH,
-ft
