### ISSUE TITLE
Interpreting percentages over 100%

### ISSUE THREAD

**Issue by CarlaAstudillo** [CareSet/COVID_Hospital_PUF#8]
Hey Fred,

Thank you so much for your help so far. I've been doing some analysis using the following formula from your FAQ: 

[**How full is the hospital with adult confirmed and suspected COVID patients?** ](https://github.com/CareSet/COVID_Hospital_PUF#how-to-make-meaningful-capacity-metrics-for-further-study)
Formula:
**total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg/ all_adult_hospital_inpatient_beds_7_day_avg**

And I noticed that there were some Texas hospitals that are reporting over 100% capacity over the whole data set. There was even one hospital that has been reporting over 600% capacity. I was wondering how you would interpret that, if these hospitals are tremendously over capacity or if these may be reporting errors. I noticed that a lot of the big percentages over 100% happened during the July 31 week which was the first week of data which may be a time when the hospitals were still getting used to reporting the data. However, this was also a time when we had peak COVID hospitalizations in Texas. That's why I'm not sure if I can completely write this off as data reporting error. 

In addition, there is also one hospital where in one week the `all_adult_hospital_inpatient_beds_7_day_avg` number goes from 161.1 to 18.3 in the next week and that number has continued to get lower and lower with the latest number (in the 11/27/2020 collection week) being 6. It reminded me a bit of the [staffed beds conversations](https://github.com/CareSet/COVID_Hospital_PUF/issues/5#issuecomment-740943213) we had in #5 issue. Would this be an example of the hospital suffering a staffing shortage these last couple of weeks? Thank you again!

**Comment by ftrotter** [comment]
Hey @CarlaAstudillo these are excellent questions. Here are some possibilities that are top of my head: 

Over 100% capacity can mean that a hospital has been overwhelmed for that much time, or it can mean that the hospital is counting its beds in a strange manner. I think the hospital itself is going to be the only one who can answer that question...

the 600% capacity is really weird, especially as it occurs over time. That to me sounds like a wholesale reporting error. 

The staffing drain issue you are describing to me only makes sense if a local region were consolidating their ICU patients to some other facilities. I would be interested to see if nearby hospitals were "ramping up" at the same time period. 

BTW if you want to give us the specific ccns you are looking at, we can pass this along to HHS and see if there is some aspect of the story that they might have... This might be somewhat faster than you just submitting a comment on the public data, but in either case we will need to start talking about specific ccn numbers... otherwise, I think you may be limited to reaching out to the hospitals directly. 

-ft

**Comment by CarlaAstudillo** [comment]
Thank you @ftrotter for your answer. There are some that seem like they're one-off mistakes. A lot of them happened on July 31 which makes me wonder if they just initially reported the number of beds wrong and then corrected themselves the subsequent weeks. However, there are a few hospitals that seem to report these kind of numbers over and over again after July 31:

- MEMORIAL HERMANN NORTHEAST HOSPITAL (450684)

- SOLARA SPECIALTY HOSPITAL MCALLEN (452095)

- SOLARA SPECIALTY HOSPITALS HARLINGEN-BROWNVILLE (452101)

- MEMORIAL HERMANN TEXAS MEDICAL CENTER (450068)

I'm pretty sure that they must be counting the beds a different way because the number of staffed beds decreases dramatically from one week to another. Nevertheless, I will reach out to them. Thank you again so much!

**Comment by ercbk** [comment]
I'm having the similar issues with COLUMBUS REGIONAL HOSPITAL (150112).  
I'm getting an above-100% value using the formula, `all_adult_hospital_inpatient_bed_occupied_7_day_avg / all_adult_hospital_inpatient_beds_7_day_avg`.  

When I compare `all_adult_hospital_inpatient_bed_occupied_7_day_avg` with `inpatient_beds_used_7_day_avg`, it does seem like they're distinguishing between adult and non-adult inpatient beds.   

But looking at `all_adult_hospital_beds_7_day_avg` and `all_adult_hospital_inpatient_beds_7_day_avg`, the numbers match. So in my case, the problem seems to be with distinguishing between inpatient and outpatient bed counts.
